### ISSUE TITLE
I followed the instructions and only have the required mods installed 

### ISSUE THREAD

**Issue by UnluckyWolfman** [Ferroxius/Vladimir-UI-EE-Patch#2]
I did a clean install and everything only have those 3 mods install but im getting this message after deleting all the scripts in the mods folder since the patch says it has the scripts essentially, but i get this error: 

Error [mod0_vladimirui_eepatch]game\player\playerinput.ws(753): I dont know any 'EES_Petard3'
Error [mod0_vladimirui_eepatch]game\player\playerinput.ws(754): I dont know any 'EES_Petard4'
Error [mod0_vladimirui_eepatch]game\player\playerinput.ws(768): I dont know any 'EES_Petard3'
Error [mod0_vladimirui_eepatch]game\player\playerinput.ws(772): I dont know any 'EES_Petard4'
Error [mod0_vladimirui_eepatch]game\player\playerinput.ws(780): Could not find function 'WmkGetQuickSlotsInstance'
Error [mod0_vladimirui_eepatch]game\player\playerinput.ws(787): Could not find function 'WmkGetQuickSlotsInstance'
Error [mod0_vladimirui_eepatch]game\player\playerinput.ws(791): Could not find function 'WmkGetQuickSlotsInstance'
Error [mod0_vladimirui_eepatch]game\player\playerinput.ws(793): I dont know any 'EES_Petard3'
Error [mod0_vladimirui_eepatch]game\player\playerinput.ws(795): Could not find function 'WmkGetQuickSlotsInstance'
Error [mod0_vladimirui_eepatch]game\player\playerinput.ws(797): I dont know any 'EES_Petard4'
Error [mod0_vladimirui_eepatch]game\player\playerinput.ws(799): Could not find function 'WmkGetQuickSlotsInstance'
Error [mod0_vladimirui_eepatch]game\player\playerinput.ws(803): Could not find function 'WmkGetQuickSlotsInstance'
Error [mod0_vladimirui_eepatch]game\player\playerinput.ws(807): Could not find function 'WmkGetQuickSlotsInstance'
Warning [mod0_vladimirui_eepatch]core\math.ws(590): Global native function 'IntToUint32' was not exported from C++ code.
Warning [mod0_vladimirui_eepatch]core\math.ws(591): Global native function 'Uint32ToInt' was not exported from C++ code.
Warning [mod0_vladimirui_eepatch]engine\environment.ws(30): Global native function 'EnableDebugOverlayFilter' was not exported from C++ code.
Warning [mod0_vladimirui_eepatch]engine\environment.ws(32): Global native function 'EnableDebugPostProcess' was not exported from C++ code.
Warning [content0]engine\showflags.ws(11): Global native function 'DebugSetEShowFlag' was not exported from C++ code.

**Comment by Ferroxius** [comment]
Fixed now in latest release hopefully

**Comment by UnluckyWolfman** [comment]
Yes it did thank you
