### ISSUE TITLE
Question about sword parry icon

### ISSUE THREAD

**Issue by UnluckyWolfman** [Ferroxius/Vladimir-UI-EE-Patch#3]
I had a quick question about the sword icon in the HUD. It doesn't seem to turn red so that one knows when to perfect parry do I have a bug or is it just like this right now due to some conflicting issues with EE Redux? Also the poise meter is also not filled in either.

**Comment by Ferroxius** [comment]
The sword icon thing was a bit of a unique thing in EE and I don't know if I can replicate it
The poise bar I am looking into fixing

**Comment by UnluckyWolfman** [comment]
Thank you for your quick replies and fixes.
