### ISSUE TITLE
Some bugs found

### ISSUE THREAD

**Issue by UnluckyWolfman** [Ferroxius/Vladimir-UI-EE-Patch#4]
Hey just wanted to report some bugs I found. One that I found is I can not see the weight that the horse is carrying there is no number next to the icon. The other one I found is that for the crafting menu the sword tab is blank and when you click on it, it shows undefined items.

**Comment by Ferroxius** [comment]
The roach weight indicator being missing is something I am aware of and have been figuring out how to fix with mixed results
The crafting menu for me doesn't seem to be broken with the exception that the subtext below the title of the item definitely saying "undefineditemsmissing" but the items in the crafting menu definitely work

**Comment by UnluckyWolfman** [comment]
The icon not appearing I guess was a random visual bug I reloaded an old save file and it fixed it some how.
